# Generated by Django 4.2.6 on 2023-10-28 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre del barrio')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024, verbose_name='nombre del candidato')),
                ('partido', models.CharField(max_length=1024, verbose_name='nombre del partido')),
                ('numero', models.CharField(max_length=3, verbose_name='numero')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre del departamento')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre del municipio')),
                ('slug', models.SlugField()),
                ('longitude', models.CharField(blank=True, max_length=1024, null=True, verbose_name='longitude')),
                ('latitude', models.CharField(blank=True, max_length=1024, null=True, verbose_name='latitude')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PuestoVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nombre Puesto de Votación')),
                ('direccion', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Dirección')),
                ('latitude', models.CharField(blank=True, max_length=1024, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=1024, null=True, verbose_name='longitude')),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.barrio')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cantidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.candidato')),
                ('puesto_votacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.puestovotacion')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024, verbose_name='nombre del barrio')),
                ('slug', models.SlugField()),
                ('puesto_votacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.puestovotacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='nombre de comuna')),
                ('slug', models.SlugField()),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='barrio',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.municipio'),
        ),
    ]
