# Generated by Django 4.2.6 on 2023-10-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='positive_integer_field',
            new_name='numero_de_votos',
        ),
    ]
