# Generated by Django 4.2.6 on 2023-10-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_mesa_nombre_remove_mesa_slug_mesa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='candidatura',
            field=models.CharField(choices=[('Alcaldía', 'Alcaldía'), ('Gobernación', 'Gobernación'), ('Concejo', 'Concejo'), ('Asamblea', 'Asamblea')], default='Alcaldía', max_length=20),
            preserve_default=False,
        ),
    ]
