# Generated by Django 3.2.16 on 2023-10-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_candidato_candidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.comuna'),
        ),
    ]
