# Generated by Django 3.2.16 on 2023-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20231029_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='partido',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='nombre del partido'),
        ),
    ]
