# Generated by Django 3.2.16 on 2023-10-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_candidato_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='numero',
            field=models.CharField(default=None, max_length=3, null=True, verbose_name='numero'),
        ),
    ]
