# Generated by Django 3.2.16 on 2023-10-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_registro_numero_de_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numero_de_votos',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
