from myapp.models import PuestoVotacion, Departamento, Municipio
from django.core.management.base import BaseCommand

PUESTOS = '''Departamento;Municipio;Nombre Puesto;Dirección;Número de mesas
SANTANDER;BUCARMANAGA;IE MAIPORÉ SEDE B;CLL 17N # 10-38 BARRIO KENNEDY;####
SANTANDER;BUCARMANAGA;IE TEC RAFAEL GARCIA HERREROS;CR 1D # N-81 - BARRIO MINUTO DE DIOS;####
SANTANDER;BUCARMANAGA;IE CAFÉ MADRID;CR 8B # 35AN-45 BARRIO CAFÉ MADRID;####
SANTANDER;BUCARMANAGA;COLEGIO FE Y ALEGRIA LOS COLORADOS;CRA 28 A # 49-50 BARRIO COLORADOS;####
SANTANDER;BUCARMANAGA;SALON COMUNAL EL PABLON;CR 11 # 61N-10 BARRIO EL PABLON;####
SANTANDER;BUCARMANAGA;CENTRO VIDA KENNEDY;CRA 12 # 16N - 43 BARRIO KENNEDY;####
SANTANDER;BUCARMANAGA;I.E. SANTO ANGEL;CLL 9N # 18C - 04 BARRIO VILLA ROSA;####
SANTANDER;BUCARMANAGA;INST DE PROM SOC DEL NORTE SEDE A;CR 22B # 1-61 BARRIO SAN CRISTOBAL;####
SANTANDER;BUCARMANAGA;ORDEN DE LOS CLÉRIGOS REG SOMASCOS;CR 26 # 11N-30 BARRIO REGADERO NORTE;####
SANTANDER;BUCARMANAGA;IE DÁMASO ZAPATA SEDE C;CLL 16N # 24-23 BARRIO VILLA HELENA;####
SANTANDER;BUCARMANAGA;IE RURAL BOSCONIA;CRA 32 # 39N-27 BARRIO BOSCONIA;####
SANTANDER;BUCARMANAGA;I.E. LA JUVENTUD SEDE A;CLL 5 N # 19 A - 12 BARRIO LA JUVENTUD;####
SANTANDER;BUCARMANAGA;UNIVERSIDAD INDUSTRIAL DE SANTANDER;CLL 9 CON CRA 27;####
SANTANDER;BUCARMANAGA;COL FRANCISCANO DEL VIRREY SOL;CLL 18 # 22-29 BARRIO SAN FRANCISCO;####
SANTANDER;BUCARMANAGA;COL SANTANDER SEDE A;CLL 9 # 25-67 BARRIO LA UNIVERSIDAD;####
SANTANDER;BUCARMANAGA;SENA - CSET - COLISEO;CRA 27 # 15-07 BARRIO SAN FRANCISCO;####
SANTANDER;BUCARMANAGA;COL AMERICANO;CR 18 # 19-22 BARRIO SAN FRANCISCO;####
SANTANDER;BUCARMANAGA;IE COMUNEROS;CR 18 # 10-20 BARRIO COMUNEROS;####
SANTANDER;BUCARMANAGA;IE CENTRO PILOTO SIMON BOLIVAR;CR 20 # 11-83 - BARRIO MUTUALIDAD;####
SANTANDER;BUCARMANAGA;COL SANTANDER SEDE C;CLL 5 # 20-14 BARRIO COMUNEROS;####
SANTANDER;BUCARMANAGA;I.E. CLUB UNION SEDE A;CLE 3 A # 10 - 36 BARRIO SAN RAFAEL;####
SANTANDER;BUCARMANAGA;INST TEC SALESIANO ELOY VALENZ;AV QUEBRADA SECA # 11-85 BARRIO GIRARDOT;####
SANTANDER;BUCARMANAGA;I. INTEGRADO JORGE ELIECER GAITAN SEDE A;CLL 16 # 9-54 BARRIO GAITAN;####
SANTANDER;BUCARMANAGA;COL FRANCISCO DE PAULA S/DER SEDE A;CR 5 OCC # 30-61 BARRIO SANTANDER;####
SANTANDER;BUCARMANAGA;COL FRANCISCO DE PAULA S/DER SEDE B;CLL 26 # 2-11 BARRIO LA FERIA;####
SANTANDER;BUCARMANAGA;CENTRAL DE ABASTOS;VIA PALENQUE CAFE MADRID # 44 - 96;####
SANTANDER;BUCARMANAGA;IE ANDRES PAEZ DE SOTOMAYOR;CLL 37 # 1-97 BARRIO LA JOYA;####
SANTANDER;BUCARMANAGA;COL COOPERATIVO DE BUCARAMANGA;CLL 45 # 0-160 BARRIO CAMPO HERMOSO;####
SANTANDER;BUCARMANAGA;SENA - CSET - SEDE SAN JUAN DE DIOS;CLL 45 # 11 - 12;####
SANTANDER;BUCARMANAGA;IE CAMPO HERMOSO;CR 9A OCC # 49-24 BARRIO CAMPO HERMOSO;####
SANTANDER;BUCARMANAGA;HOSPITAL PSIQUIATRICO SAN CAMILO;CLL 45 N 7 18;####
SANTANDER;BUCARMANAGA;IE JORGE ARDILA DUARTE SEDE A;CLL 53 # 21-25 BARRIO LA CONCORDIA;####
SANTANDER;BUCARMANAGA;INST SAN JOSÉ DE LA SALLE;CRR 21 #68-45 BARRIO LA VICTORIA;####
SANTANDER;BUCARMANAGA;COL TEC EMPRESARIAL JOSE MARIA;CLL 51 #13-97 BARRIO SAN MIGUEL;####
SANTANDER;BUCARMANAGA;COL AURELIO MARTINEZ MUTIS SEDE B;CLL 56 # 21-52 BARRIO LA CONCORDIA;####
SANTANDER;BUCARMANAGA;GIMNASIO SUPERIOR EMPRESARIAL;CLL 67 # 11-29 BARRIO LA VICTORIA;####
SANTANDER;BUCARMANAGA;IE SANTA MARIA GORETTI SEDE C;CLL 65 OCC # 18 - 08 BARRIO LA VICTORIA;####
SANTANDER;BUCARMANAGA;COL AURELIO MARTINEZ MUTIS SEDE A;AV LOS ESTUDIANTES # 9-313 BARRIO REAL DE MINAS;####
SANTANDER;BUCARMANAGA;IE NUESTRA SEÑORA DEL PILAR SEDE A;AV LOS ESTUDIANTES # 9-323 BARRIO REAL DE MINAS;####
SANTANDER;BUCARMANAGA;UNIDADES TECNOLOGICAS DE SANT;AV LOS ESTUDIANTES # 9-82 BARRIO REAL DE MINAS;####
SANTANDER;BUCARMANAGA;IE NUESTRA SEÑORA DEL PILAR SEDE B;CLL 65C # 6A - 08 BARRIO LOS CANELOS;####
SANTANDER;BUCARMANAGA;IE NUESTRA SEÑORA DEL PILAR SEDE E;CR 10C # 68A - 13 BARRIO PABLO VI;####
SANTANDER;BUCARMANAGA;IE INEM CUSTODIO GARCIA ROV SEDE H;CLL 67A # 9 - 61 BARRIO BUCARAMANGA;####
SANTANDER;BUCARMANAGA;IE LA LIBERTAD;CR 31 # 101 - 24 BARRIO LA LIBERTAD;####
SANTANDER;BUCARMANAGA;IE INEM CUSTODIO GARCIA ROVIRA SEDE G;CR 32 # 87 - 86 BARRIO SAN MARTIN;####
SANTANDER;BUCARMANAGA;COL. INTEGRADO JORGE ISAAC;CLL 106 No 29-47 BARRIO DIAMANTE I;####
SANTANDER;BUCARMANAGA;IE PROVENZA;CR 23 # 109 - 07 BARRIO PROVENZA;####
SANTANDER;BUCARMANAGA;IE INEM CUSTODIO GARCIA ROV SEDE E;CLL 91 # 25 - 82 BARRIO DIAMANTE II;####
SANTANDER;BUCARMANAGA;JARDIN INFANTIL CASITA DE CHOC;CR 17C # 90A - 02 BARRIO SAN LUIS;####
SANTANDER;BUCARMANAGA;IE INEM CUSTODIO GARCIA ROV SEDE A;CR 19A # 104 - 56 BARRIO PROVENZA;####
SANTANDER;BUCARMANAGA;COL ADVENTISTA LIBERTAD;CR 15 # 103D - 160 BARRIO DELICIAS ALTAS;####
SANTANDER;BUCARMANAGA;IE MEDALLA MILAGROSA;CR 7B # 103 - 24 BARRIO EL PORVENIR;####
SANTANDER;BUCARMANAGA;IE INEM SEDE D;CRA 15 No 107 63 BARRIO DANGOND;####
SANTANDER;BUCARMANAGA;COL DE LAS AMERICAS;CLL 51 # 24 - 20 BARRIO NUEVO SOTOMAYOR;####
SANTANDER;BUCARMANAGA;COL SAN PEDRITO;CLL 63 # 32 - 76 BARRIO CONUCOS;####
SANTANDER;BUCARMANAGA;UNIVERSIDAD AUTONOMA DE BUCARAMANGA;AV 42 # 48 - 11 BARRIO EL JARDIN;####
SANTANDER;BUCARMANAGA;COL SAN PEDRO CLAVER;CR 28 # 47 - 06 BARRIO SOTOMAYOR;####
SANTANDER;BUCARMANAGA;EFORSALUD;CLL 48 # 27 - 64 BARRIO SOTOMAYOR;####
SANTANDER;BUCARMANAGA;COLEGIO LA PRESENTACION;CLE 56 # 33 - 38 BARRIO CABECERA DEL LLANO;####
SANTANDER;BUCARMANAGA;CEN DE SERVICIOS UNIVERSITARIOS CSU UNAB;CRA 47 N 53 78 BARRIO TERRAZAS;####
SANTANDER;BUCARMANAGA;ESC NORMAL SUPERIOR SEDE A;CLL 30 # 27-163 BARRIO AURORA;####
SANTANDER;BUCARMANAGA;ESC NORMAL SUPERIOR SEDE C;CLL 30 # 26 - 45 BARRIO ANTONIA SANTOS;####
SANTANDER;BUCARMANAGA;COL PSICOPEDAG CARL ROGERS;CR 25 # 31 - 94 BARRIO ANTONIA SANTOS;####
SANTANDER;BUCARMANAGA;COOP ESPECIALIZ DE EDUC DE COMFENALCO;CLL 37 #21-34 PARQUE BOLIVAR;####
SANTANDER;BUCARMANAGA;UNIVERSIDAD COOP DE COLOMBIA;CLL 30A # 33 - 51 BARRIO QUINTADANIA;####
SANTANDER;BUCARMANAGA;I.E. LAS AMERICAS;CLL 33 # 36 - 16 BARRIO ALVAREZ;####
SANTANDER;BUCARMANAGA;IE BICENTENARIO SEDE B;CLL 34 # 45 - 38 BARRIO ALVAREZ;####
SANTANDER;BUCARMANAGA;I.E. ORIENTE MIRAFLORES SEDE A;KM 2 VIA PAMPLONA 50 - 46 BARRIO ALBANIA;####
SANTANDER;BUCARMANAGA;I.E. ORIENTE MIRAFLORES SEDE C;CL 20 # 53-36 KM 4 VIA PAMPLONA BARRIO MIRAFLORES;####
SANTANDER;BUCARMANAGA;IE MIRAFLORES SEDE D BUENOS AIRES;CLL 17 # 57 - 35 BARRIO BUENOS AIRES;####
SANTANDER;BUCARMANAGA;IE TECNICO DAMASO ZAPATA SEDE B;CLL 7A N 38 48 BARRIO VEGAS DE MORRORICO;####
SANTANDER;BUCARMANAGA;GOBERNACION DE SANTANDER;CLL 37 No 10-36 BARRIO GARCIA ROVIRA;####
SANTANDER;BUCARMANAGA;CORP UNIVERSITARIA UNICIENCIA;CLL 37 # 11 - 58 BARRIO EL CENTRO;####
SANTANDER;BUCARMANAGA;COL NUESTRA SEÑORA DE FATIMA;CR 12 # 41 - 69 BARRIO EL CENTRO;####
SANTANDER;BUCARMANAGA;INST CALDAS;CIRCUNV 35 # 92 - 135 BARRIO TEJAR MODERNO;####
SANTANDER;BUCARMANAGA;COL NUESTRA SEÑORA DEL ROSARIO;CR 55 # 72 - 02 BARRIO LAGOS DEL CACIQUE;####
SANTANDER;BUCARMANAGA;GIMNASIO CAMPESTRE SAN SEBASTIAN;CRA 53 N 73 83 BARRIO LAGOS DEL CACIQUE;####
SANTANDER;BUCARMANAGA;I.E. JOSE CELESTINO MUTIS;CR 3W # 57 - 14 BARRIO MUITS;####
SANTANDER;BUCARMANAGA;I.E. LUIS CARLOS GALAN SARMIENTO;CLL 59 # 38W - 00 BARRIO ESTORAQUES;####
SANTANDER;BUCARMANAGA;I.E. NUESTRA SEÑORA DEL PILAR SEDE C;CLL 65 CR 11W ESQ BARRIO MONTERREDONDO;####
SANTANDER;BUCARMANAGA;INST NAL PENITEN Y CARCELARIO HOMBRES;CLL 45 # 6-75 BARRIO CAMPO HERMOSO;####
SANTANDER;BUCARMANAGA;INST NAL PENITEN Y CARCELARIO MUJERES;KM 3 VIA CHIMITA PALENQUE;####
SANTANDER;BUCARMANAGA;EL PABLON;CENT EDUC RURAL EL PAULON;####
SANTANDER;BUCARMANAGA;IE RURAL VIJAGUAL;COL RURAL VIJAGUAL;####
SANTANDER;BUCARMANAGA;LA CAPILLA;ESC RURAL LA CAPILLA;####
SANTANDER;BUCARMANAGA;MONSERRATE;KIOSCO DEL PARQUE - MONSERRATE;####
SANTANDER;BUCARMANAGA;SAN JOSE;ESC RURAL SAN JOSÉ;####
SANTANDER;BUCARMANAGA;IE LA MALAÑA;KM 1 VIA AL ACUEDUCTO;####'''


class Command(BaseCommand):
    def handle(self, *args, **options):

        if PUESTOS:
            puestos = PUESTOS.split('\n')

            for puesto in puestos:
                data = puesto.split(';')
                if len(data)>1:
                    departamento = data[0]
                    municipio = data[1]
                    nombre = data[2]
                    direccion = data[3]
                    numero_mesa = data[4]
                    if not PuestoVotacion.objects.filter(
                        departamento__name=departamento,
                        municipio__name=municipio,
                        # barrio__name=barrio,
                        nombre=nombre,
                    ).exists():
                        if not Departamento.objects.filter(name=departamento).exists():
                            departamento_object = Departamento(name=departamento)
                            departamento_object.save()

                        else:
                            departamento_object = Departamento.objects.filter(name=departamento).first()

                        if not Municipio.objects.filter(name=municipio, departamento__name=departamento).exists():
                            print(">>> Municipio with label: '{}' created".format(municipio))
                            municipio_object = Municipio(name=municipio, departamento=departamento_object)
                            municipio_object.save()
                        else:
                            municipio_object = Municipio.objects.filter(name=municipio).first()

                        puesto_obj = PuestoVotacion(
                            nombre=nombre,
                            direccion=direccion,
                            departamento=departamento_object,
                            municipio=municipio_object
                        )
                        puesto_obj.save()
                        print(">>> puesto: '{}' created".format(nombre))